### ISSUE TITLE
stale branches

### ISSUE THREAD

**Issue by albeanth** [OSURadTransportReactorPhysics/transportGroup#159]
So I screwed up (but I don't think it will affect anything) and made a PR for the master branch rather than the gh-pages branch. But it got me to thinking... what do you guys think about deleting the old branches we don't use? Namely "doug-edit-theme" and the "revert-*-gh-pages" branches? Maybe even deleting the master branch?

**Comment by dougwoods3** [comment]
Yeah, I support deleting things that are obsolete.

**Comment by albeanth** [comment]
we can also protect the gh-pages branch. 

check it out in settings

**Comment by albeanth** [comment]
@rtrp/admins you guys ok with me cleaning house here? I will keep the gh-pages (obviously) and master for now. might 'protect' gh-pages

**Comment by dougwoods3** [comment]
Yes.

**Comment by albeanth** [comment]
Done.
