### ISSUE TITLE
Rearranging gh-pages

### ISSUE THREAD

**Issue by albeanth** [OSURadTransportReactorPhysics/transportGroup#16]
Hey guys - I'm going to raise the topic of restructuring gh-pages. Can we put the users directories into subdirectories? To look something like this:

~/rtrp/osu-transport/gh-pages/users/<username>

By doing this we can clean up the gh-pages main directory a bit. If you guys have any problems with that or have other ideas on how we can clean up the gh-pages main directory, I'm all ears.

**Comment by dougwoods3** [comment]
I don't think I care.

I want to add my notes on using the local cluster on Rogue and stuff from these parallel classes. So a directory for research or support or computing or something would be useful.

**Comment by albeanth** [comment]
@dougwoods3 what do you mean? Do you want to have links(?) on your personal page with class/research notes? I don't think I'm getting what you are throwing down haha

**Comment by dougwoods3** [comment]
Oh, I just want to copy it all over to here so it is common and available to our group. I have it started on my [OSU wiki](https://web.engr.oregonstate.edu/~woodsdou/wiki/HomePage).

**Comment by albeanth** [comment]
@dougwoods3 ahh I see. So have another tab (or something) for general wiki information on compiling specific things, where to look for information, etc... 

@harterj I like it.

**Comment by harterj** [comment]
Ok, yes I see the value in a /users/, I'll get that done later tonight so the directory structure stays kosher.

I think we can definitely add a "Wiki" tab - I (or someone) just needs to figure that out in HTML - because while everyone is meant to write a markdown for their own page / wikis or whatever, the main site is HTML - cannot do real fancy stuff in markdown.

**Comment by harterj** [comment]
also, before we go much further we should let Palmer know as well as Jens...I dont want to do this all if we can't have the site linked to on ne.oregonstate.edu
@albeanth @dougwoods3

**Comment by albeanth** [comment]
@harterj  I think we are about to a good spot to show it to Jens and Palmer. 

I don't know if they need to see the github page (considering they do not use git) but they should have a link to the website and be aware what we are capable of and where we envision it going. 

we should be able to tell them that control of the account is transferrable once we leave - and that personal pages are totally up to the users to update and that @rtrp/admins control what goes on and what does not. 

The only issues I forsee are logistics with the university and it not being through the universities system - like Kyle was trying to do.

**Comment by harterj** [comment]
Ok. I will write something up and CC @albeanth and @dougwoods3 . I think everything you said makes sense.
