### ISSUE TITLE
Wiki page

### ISSUE THREAD

**Issue by albeanth** [OSURadTransportReactorPhysics/transportGroup#17]
@dougwoods3 shouldn't the wiki page be directly on our website? rather than in the wiki tab on github? I feel like it will be easier for the general public to navigate rather than on the github website.

**Comment by albeanth** [comment]
@dougwoods3 unless the wiki tab you made on the github website is directed more for new members to make their own page and familiarize themselves with the git work flow.... that would make sense. 

and then put compiling notes, how to's, etc, on the actual website....

**Comment by dougwoods3** [comment]
@albeanth Everything is edited from GitHub so I think that is where the how to's should be. The main site should be the end product.

**Comment by dougwoods3** [comment]
@albeanth The README.md file might be a place to put this info also. I don't know what the etiquette is for this.

**Comment by dougwoods3** [comment]
@albeanth That was really confusing. I guess I didn't really read what you wrote. How to GitHub in this Wiki. The info about Rogue and OpenCL/OpenGL and whatever else on the actual webpage.

**Comment by harterj** [comment]
Yes. I feel like there should be a "Wiki" tab on rtrp.github.io/osu-transport that someone can click on and see everything we've Wiki'ed. Is that what @dougwoods3 and @albeanth are saying?

**Comment by albeanth** [comment]
@dougwoods3 yes. I agree. Below is what I wrote before your latest comment. 

# 

# 

@dougwoods3 I don't either. That's why I'm raising these issue topics. So we can figure out what we like/think is best. 

I like the idea of putting how to's for our _own research group_ - i.e. those who we anticipate will be cloning gh-pages and submitting pull requests - on the wiki on Github and/or on the README. In other words, a how to for how the actual flow of the /osu-transport repo works. 

But I feel like we should put general how to's (like how to use tiks or latex pointers, or beamer, or gnuplot, or whatever) on the actual website under a wiki tab/link or something.

**Comment by dougwoods3** [comment]
@albeanth @harterj Tony's last message is what I mean.

**Comment by albeanth** [comment]
since we got the all clear, we should make a push to have this ready to go for the group to use once classes start back up. As in having a clear _**github side**_ wiki on how to get information up and understanding the workflow of git.

**Comment by dougwoods3** [comment]
yep. School starts Sep 20 ish? Give everybody 2 weeks to get their pages set up, Sep. 6. Gives us like 3 weeks to write the wiki to give everybody directions on how to do their page.

**Comment by albeanth** [comment]
Classes start [September 21st](http://catalog.oregonstate.edu/ChapterDetail.aspx?key=148). So from today, we have 6 weeks to get the _**github side**_ wiki done.

**Comment by dougwoods3** [comment]
6 weeks minus the amount of time to give everybody a chance to create their pages.

**Comment by albeanth** [comment]
Sure. Personally, I think getting the wiki done properly should be a priority. People will want to format their pages their own way with their own content. But unless we have a bulletproof wiki they won't know how to and our website won't get updated :/

**Comment by harterj** [comment]
I assign @albeanth to write the wiki

**Comment by albeanth** [comment]
@harterj @dougwoods3  Ok. I will do it.

**Comment by albeanth** [comment]
I just thought it would be good to have an example .bash_profile / .bashrc file on the website wiki. I wanted to write that idea down and didn't know where else to write it haha

**Comment by dougwoods3** [comment]
@albeanth I like the idea because I'm curious to see yours but that seems like it could go in the How to _Use Rogue and Compute in Parallel and Use MCNP and Other Things that You Want to Learn Good Too_ link on the main page.

Maybe that's what you mean by website wiki.

**Comment by albeanth** [comment]
@dougwoods3 that's exactly what I mean by the website wiki. 

I was talking to @harterj about this the other night. We kind of need to establish some nomenclature on this. When I say the **github wiki** I mean the wiki page that is on the **github website**. When I say the **website wiki** I mean the wiki page on **rtrp.github.io/osu-transport**. 

If that nomenclature works for you guys I'm for using that.

**Comment by dougwoods3** [comment]
@albeanth word.

**Comment by harterj** [comment]
@dougwoods3 👍  for this "_Use MCNP and Other Things that You Want to Learn Good Too_" hahahah made me laugh out loud
