### ISSUE TITLE
git blob

### ISSUE THREAD

**Issue by harterj** [OSURadTransportReactorPhysics/transportGroup#175]
@dougwoods3 how did you do the video upload? git blob?

**Comment by dougwoods3** [comment]
Oh i think i just uploaded the video as a zip file. So the link just
downloads and unzips the video.

**Comment by dougwoods3** [comment]
Dang, looking at this on my computer now, I don't know what I did. I see that you uploaded your mp4 file though. So maybe just create a clickable link to it on your page?

**Comment by harterj** [comment]
I tried to do that, just says some business about file not found. Added the raw=true statement to the end of the file now, maybe that'll fix it

**Comment by harterj** [comment]
yep! at end of the file url, adding "?raw=true" seems to allow downloads.
