### ISSUE TITLE
New Admins

### ISSUE THREAD

**Issue by albeanth** [OSURadTransportReactorPhysics/transportGroup#179]
* @rtrp/admins I think it is about time we start the discussion of assigning new admins to the site. 

* @dougwoods3 @harterj do you want to stay involved with the site? If so, to what degree? 

* @dougwoods3 this might be a good time to make an alumni section!

**Comment by dougwoods3** [comment]
@rtrp/admins We could ask for volunteers to admin.

@albeanth I might stay on for a while to help admin the site. I think an alumni section would be great. Future little Todd's can use it to connect with us when we become adults at labs.

**Comment by albeanth** [comment]
@dougwoods3  hahahaha "little Todd's"... love it.

`I might stay on for a while to help admin the site.`
👆 sounds good man. I just figured I would bring it up since you aren't going to be on campus much this coming year (🤞 for you).

**Comment by harterj** [comment]
@albeanth @dougwoods3

I don’t know immediately who a new admin would be. I agree with an alumni section for sure

**Comment by albeanth** [comment]
@harterj I know Aaron Reynolds has been using GitHub a bit so his name comes to mind for me.

**Comment by harterj** [comment]
@albeanth Whoever is active and would want to take charge..so AR is fine by me..we ought to ask him, then add him so he can see what we have been doing so far, and then put him in charge of the next few PRs

**Comment by albeanth** [comment]
Sounds good. When/are you coming back to campus?

On Aug 20, 2018 1:38 PM, "Jackson Harter" <notifications@github.com> wrote:

@albeanth <https://github.com/albeanth> Whoever is active and would want to
take charge..so AR is fine by me..we ought to ask him, then add him so he
can see what we have been doing so far, and then put him in charge of the
next few PRs

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/rtrp/osu-transport/issues/179#issuecomment-414455042>,
or mute the thread
