### ISSUE TITLE
Mobile support

### ISSUE THREAD

**Issue by albeanth** [OSURadTransportReactorPhysics/transportGroup#18]
I have a feeling this is potentially a way long term item. Have either of you looked at the website on your phone? or tablet or anything? it doesn't look too great. 

If we get the green light from Palmer/Jens/university to continue to hone this thing in, it might be worth while optimizing the layout for mobile use. 

Again, this is potentially waay the heck out there.

**Comment by harterj** [comment]
It looks good if there's no picture in the sidebar..but yes, need to fix this eventually.
