### ISSUE TITLE
Security Issues

### ISSUE THREAD

**Issue by nickwhitman1993** [OSURadTransportReactorPhysics/transportGroup#182]
@rtrp/admins 

Need to fix security issues again

**Comment by albeanth** [comment]
@aaronjamesreynolds noticed this after he merged in PR #181 . Let's assign him to it! 😁 

As an aside, while we're here, I spoke with @harterj about approving PR requests today. We concluded,(and @harterj correct me if I misinterpreted this) that moving forward, to approve a PR, we will require only 2 admins to review a PR before a merge. 

That way we won't have to wait for all 5(?) of us to approve something.

**Comment by nickwhitman1993** [comment]
@albeanth Sounds good. I think that's a good idea 💡

**Comment by aaronjamesreynolds** [comment]
So, we got three issues in Gemfile.lock:

1.  **rubyzip:** this *should* be a simple fix. Already sorted this one out.
2.  **loofah**: don't know why this is cropping up. From what I can tell, loofah has the recommended versioning each place it occurs.
3.  **jekyll**: this guy comes up in **many** places. My concern is that we may break something in updating everything to the recommended version.

Also, let me tell you what, I got no idea what Gemfile.lock does. I'll do some investigating, but bear with me. Any thoughts or tips are welcome!

**Comment by albeanth** [comment]
@aaronjamesreynolds jekyll is a local server(?) of sorts that allows you to view your local changes on the website (the ones on your fork) before you submit a PR.

It was something that was kind of a pain to set up so we never really pushed it on folks. As for what the Gemfile.lock does, I also have no clue... just one of those required files for the website

**Comment by aaronjamesreynolds** [comment]
Is it a feature anyone continues to use? Can we just ax Gemfile and Gemfile.lock altogether? That would alleviate current and (probably) future security vulnerabilities.

**Comment by aaronjamesreynolds** [comment]
And satisfy my need for destruction.

**Comment by harterj** [comment]
Not essential to have them in place. The only reason we were using Jekyll was when we were learning the markdown style and how it would look before the website was pushed live. It's a nice tool for anyone who is learning how to do this...unfortunately, and seemingly par for the course, I did not document the methods for using Jekyll...

Since I will be phased out eventually, I will pass this decision to you and @nickwhitman1993.

**Comment by aaronjamesreynolds** [comment]
What do you think, @nickwhitman1993 ?

**Comment by nickwhitman1993** [comment]
@aaronjamesreynolds 

My vote is to get rid of it. If we want, we can bring it back later.

**Comment by albeanth** [comment]
@rtrp/admins as Jackson said, I think it was a really effective tool for when we first started getting the website going. We were pushing lots of things that we had no idea if they would work or not and it was a good way to double check things before they were put into a PR. 

Moving forward, I think it will be fine to get rid of Jekyll, for now. I think that if someone in the (near?) future decides to change the theme/layout of the webpage it may be nice to have Jekyll (or some equivalent) to showcase proposed changes in a PR (via a screenshot or something) before pushing them into a PR. 

*Edit*
This could be a nice side task for anyone who is interested. We could start a git "project" via the tabs up top and assign one/a few of the group members to it. Try and get a little more involvement from the group.

**Comment by nickwhitman1993** [comment]
Closing issue per above.
