### ISSUE TITLE
Move Tony to RTRP Alumni

### ISSUE THREAD

**Issue by nickwhitman1993** [OSURadTransportReactorPhysics/transportGroup#189]
Move @albeanth to RTRP Alumni section @rtrp/admins 

Also, I think we should do something in memoriam of Doug. I'd like to discuss what you all think might be appropriate or respectful considerations.

**Comment by albeanth** [comment]
>Move @albeanth to RTRP Alumni section

Do it to it. I _really_ need to update my page.

As for doing something for Doug, I think that's a great idea and a discussion on what we should do should certainly take place.

**Comment by albeanth** [comment]
Also, @zachthills and @pharnb should be moved to alumni as well.

**Comment by aaronjamesreynolds** [comment]
Whoops let me move Ben Pharn, too. Pretty sure Zach Hills is a student still. Just out at INL.

**Comment by aaronjamesreynolds** [comment]
What about @Aarontama ?

**Comment by albeanth** [comment]
Someone should get in touch with @pharnb - and other alumn - if he'd like to use his gh page or point it elsewhere (e.g. company page for a new job, etc).

**Comment by albeanth** [comment]
@rtrp/admins this issue ready to be closed?

**Comment by nickwhitman1993** [comment]
@rtrp/admins closing this issue.
