### ISSUE TITLE
update admins

### ISSUE THREAD

**Issue by albeanth** [OSURadTransportReactorPhysics/transportGroup#191]
I think it may be time to remove myself, @harterj, and @dougwoods3 as admins from the RTRP website and officially hand the keys over.

@rtrp/admins thoughts?

**Comment by nickwhitman1993** [comment]
@rtrp/admins It sounds good. Let's make it so.

**Comment by albeanth** [comment]
@nickwhitman1993 I'll update the ownership of the page to you and @aaronjamesreynolds soon. Then you two will be running the ship!

**Comment by harterj** [comment]
Yep. It is time for this. I feel comfortable with the reins in the hands of the new staff. Hail to the new chiefs!

**Comment by nickwhitman1993** [comment]
I believe this issue has now been settled. Thanks all!
