### ISSUE TITLE
RTRP Alumni Pages

### ISSUE THREAD

**Issue by albeanth** [OSURadTransportReactorPhysics/transportGroup#213]
@rtrp/admins I just poked around the webpages for the alumni. I think it's awesome that you guys are working on a memoriam for Doug. If there's anything I can do, just let me know. I'd be happy to help any way I can.

I'm not sure if it's on your radar or not, but Aaron Tamashiro and Ben Pharn's pages could use a little attention. I'd suggest linking their pages to either their new jobs or simply having their links be to an email address. In their current state, their pages seem dated.

**Comment by ryanstwrt** [comment]
@albeanth The memoriam was Nick's idea, and I think it'll be really nice once we get it all set up.

I agree on updating Aaron/Ben's page. It might be cool if we can update their page and get a link to their master's thesis.

**Comment by aaronjamesreynolds** [comment]
That's a good idea. 

Here's the link for Aaron's: https://ir.library.oregonstate.edu/concern/graduate_thesis_or_dissertations/sb397f11f

Here's Ben's:  https://ir.library.oregonstate.edu/concern/graduate_thesis_or_dissertations/cn69m9553

**Comment by ryanstwrt** [comment]
#214 Should be in the works to solve this problem!

**Comment by albeanth** [comment]
@ryanstwrt just a few comments/edits on #214. 

Thanks guys, you are killing it! Doing us OG admins proud 👍
