### ISSUE TITLE
Current and Past Students

### ISSUE THREAD

**Issue by dougwoods3** [OSURadTransportReactorPhysics/transportGroup#26]
Should we add a directory for all of the past students? So when Lara leaves, her link gets moved into the "Past" directory.

**Comment by dougwoods3** [comment]
So her page is still accessible to the public.

**Comment by albeanth** [comment]
I'm fine with that.

**Comment by harterj** [comment]
Sure, but not on the main page. If we link to past students, can we make it a link on the sidebar, by the Wiki link?

**Comment by albeanth** [comment]
@harterj that's fine. Maybe we should just move to the new format - with a sidebar. If you could do that and in the pull request attach a screenshot of what it will look like that would be great (because I don't think we will have any way of looking at it without merging it; if that makes sense...)

**Comment by harterj** [comment]
@albeanth @dougwoods3 Ok. I'll look at the sidebar option this evening. Will do about the screenshot.

**Comment by dougwoods3** [comment]
$test$
$O \left( \epsilon \right)$

**Comment by albeanth** [comment]
@dougwoods3 can't you test markdown by hitting the preview button instead of making a comment?

**Comment by dougwoods3** [comment]
@albeanth sometimes. The reference [^1] doesn't preview, but it works on the actual site. I was wondering the same for math.
