### ISSUE TITLE
Separating out students on main page

### ISSUE THREAD

**Issue by albeanth** [OSURadTransportReactorPhysics/transportGroup#94]
@rtrp/admins  I've been thinking about this for awhile (and I know I've brought it up) but what do you guys think about separating out the students into a tabular format. 

Example:

### PhD 
- Jackson
- Doug
- Rob
...etc

### Masters
- Person A
- Person B
- etc...

### Undergrads
- Person C
- Person D
- etc...

**Comment by harterj** [comment]
Dig it, but expand PhD to Doctoral to keep it consistent with Masters, and then Undergraduate, etc.

**Comment by albeanth** [comment]
Works for me. So who knows how to edit HTML? haha

**Comment by harterj** [comment]
I can give it a look over a couple days from now, sure. I think we just want to add a line separator and those three tabs

**Comment by dougwoods3** [comment]
Eh, I don't think we need to separate "us" from "them". Each page should speak for itself for what degree we're seeking.

My feelings stem from not wanting to be (or seem) elitist.

**Comment by albeanth** [comment]
I agree with not wanting to be elitist. It was more of an organizational idea than anything else. Just with so many students it is seeming a little cluttered (or maybe that's just me).

**Comment by dougwoods3** [comment]
Functionally, i think the site is to show off our group's research; the research that OSU nukular pumps out. Our individual pages serve as the "who am I", "what degree we're seeking", "what research did I do?"

So actually, I wonder if we could group individuals by research topic. For decluttering (you're right, tony. it is pretty cluttered).

**Comment by albeanth** [comment]
Oooooh I like that. I vote we do that rather than separating out by degree.

**Comment by dougwoods3** [comment]
Rad Transport
Reactor physics
UQ?
Space?
security/safeguards?

**Comment by harterj** [comment]
@rtrp/admins Okay, I like the research categories. I think we can use the meeting this week to get an idea of the categories of research and then make an update accordingly.

**Comment by dougwoods3** [comment]
Rad transport: tony, jackson, doug, adam, jackson 2, nick
core design/fuel analysis: pavel, aaron, emroy, rob
safeguard/security: ben p
UQ: kyle

**Comment by dougwoods3** [comment]
ben L to UQ

**Comment by robertschickler** [comment]
They should be divided into Alphas, Betas and Gammas.

*sips soma*

**Comment by dougwoods3** [comment]
I'd prefer to be a positron.

**Comment by albeanth** [comment]
@rtrp/admins  hey dudes - do you guys still want to do this?

**Comment by dougwoods3** [comment]
I almost started to work on this today but started studying for my midterm instead. So, yes, eventually.

**Comment by albeanth** [comment]
I would take a stab at it I just don't know html that well. /(am feeling too lazy to learn haha)

**Comment by dougwoods3** [comment]
I've never used it. I say let'r rip.

**Comment by harterj** [comment]
bumping this 👍

**Comment by harterj** [comment]
@rtrp/admins  I started a draft, I'll do a PR on it when I finish..pretty soon

**Comment by harterj** [comment]
I figured I had time since I don't have to rush to write up anything for ANS San Fran

**Comment by harterj** [comment]
@rtrp/admins Also, I'd like to eventually add a paragraph or two on "what we're about", approved by TP of course...but just sort of an opener to the site. So I'd ask you guys to help think of stuff like that?

**Comment by albeanth** [comment]
@harterj for the "what we're about" start a new issue?
